-- MySQL Script generated by MySQL Workbench
/-- Mon Nov 18 22:43:10 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema logindb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema logindb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `logindb` DEFAULT CHARACTER SET utf8 ;
USE `logindb` ;

-- -----------------------------------------------------
-- Table `logindb`.`user_app`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logindb`.`user_app` (
  `iduser_app` INT NOT NULL AUTO_INCREMENT,
  `sso_id` VARCHAR(45) NOT NULL,
  `pwd_hash` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `del` TINYINT NULL,
  PRIMARY KEY (`iduser_app`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  UNIQUE INDEX `sso_id_UNIQUE` (`sso_id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logindb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logindb`.`role` (
  `idRole` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `codRole` VARCHAR(45) NOT NULL,
  `del` TINYINT NOT NULL,
  PRIMARY KEY (`idRole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logindb`.`jeuNoel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logindb`.`jeuNoel` (
  `idjeuNoel` INT NOT NULL AUTO_INCREMENT,
  `user_app_iduser_app` INT NOT NULL,
  `jour1` VARCHAR(1) NOT NULL DEFAULT 'N',
  `jour2` VARCHAR(1) NOT NULL DEFAULT 'N',
  `jour3` VARCHAR(1) NULL DEFAULT 'N',
  `jour4` VARCHAR(1) NULL DEFAULT 'N',
  `jour5` VARCHAR(1) NULL DEFAULT 'N',
  `jour6` VARCHAR(1) NULL DEFAULT 'N',
  `jour7` VARCHAR(1) NULL DEFAULT 'N',
  `jour8` VARCHAR(1) NULL DEFAULT 'N',
  `jour9` VARCHAR(1) NULL DEFAULT 'N',
  `jour10` VARCHAR(1) NULL DEFAULT 'N',
  `jour11` VARCHAR(1) NULL DEFAULT 'N',
  `jour12` VARCHAR(1) NULL DEFAULT 'N',
  `jour13` VARCHAR(1) NULL DEFAULT 'N',
  `jour14` VARCHAR(1) NULL DEFAULT 'N',
  `jour15` VARCHAR(1) NULL DEFAULT 'N',
  `jour16` VARCHAR(1) NULL DEFAULT 'N',
  `jour17` VARCHAR(1) NULL DEFAULT 'N',
  `jour18` VARCHAR(1) NULL DEFAULT 'N',
  `jour19` VARCHAR(1) NULL DEFAULT 'N',
  `jour20` VARCHAR(1) NULL DEFAULT 'N',
  `jour21` VARCHAR(1) NULL DEFAULT 'N',
  `jour22` VARCHAR(1) NULL DEFAULT 'N',
  `jour23` VARCHAR(1) NULL DEFAULT 'N',
  `jour24` VARCHAR(1) NULL DEFAULT 'N',
  PRIMARY KEY (`idjeuNoel`),
  INDEX `fk_jeuNoel_user_app1_idx` (`user_app_iduser_app` ASC) ,
  CONSTRAINT `fk_jeuNoel_user_app1`
    FOREIGN KEY (`user_app_iduser_app`)
    REFERENCES `logindb`.`user_app` (`iduser_app`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logindb`.`user_app_has_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logindb`.`user_app_has_role` (
  `user_app_iduser_app` INT NOT NULL,
  `role_idRole` INT NOT NULL,
  PRIMARY KEY (`user_app_iduser_app`, `role_idRole`),
  INDEX `fk_user_app_has_role_role1_idx` (`role_idRole` ASC) ,
  INDEX `fk_user_app_has_role_user_app_idx` (`user_app_iduser_app` ASC) ,
  CONSTRAINT `fk_user_app_has_role_user_app`
    FOREIGN KEY (`user_app_iduser_app`)
    REFERENCES `logindb`.`user_app` (`iduser_app`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_app_has_role_role1`
    FOREIGN KEY (`role_idRole`)
    REFERENCES `logindb`.`role` (`idRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logindb`.`Cadeau`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logindb`.`Cadeau` (
  `idCadeau` INT NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(100) NULL,
  `Agagner` DATE NULL,
  `dateGain` DATE NULL,
  `user_app_iduser_app` INT NULL,
  PRIMARY KEY (`idCadeau`),
  INDEX `fk_Cadeau_user_app1_idx` (`user_app_iduser_app` ASC) ,
  CONSTRAINT `fk_Cadeau_user_app1`
    FOREIGN KEY (`user_app_iduser_app`)
    REFERENCES `logindb`.`user_app` (`iduser_app`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logindb`.`tirage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logindb`.`tirage` (
  `idtirage` INT NOT NULL AUTO_INCREMENT,
  `datetir` DATE NULL,
  `Cadeau_idCadeau` INT NOT NULL,
  `user_app_iduser_app` INT NOT NULL,
  PRIMARY KEY (`idtirage`),
  INDEX `fk_tirage_Cadeau1_idx` (`Cadeau_idCadeau` ASC) ,
  INDEX `fk_tirage_user_app1_idx` (`user_app_iduser_app` ASC) ,
  CONSTRAINT `fk_tirage_Cadeau1`
    FOREIGN KEY (`Cadeau_idCadeau`)
    REFERENCES `logindb`.`Cadeau` (`idCadeau`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tirage_user_app1`
    FOREIGN KEY (`user_app_iduser_app`)
    REFERENCES `logindb`.`user_app` (`iduser_app`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE messages (
    id INT PRIMARY KEY AUTO_INCREMENT,
    message VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL
)ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
