/*
-- Query: SELECT * FROM logindb.cadeau
LIMIT 0, 1000

-- Date: 2019-11-27 23:42
*/
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Machine a pop corn','2019-12-01',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Machine a pop corn','2019-12-12',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Machine a pop corn','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Machine a café Nespresso','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Machine a café Nespresso','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Machine a café Nespresso','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un magnum champagne Mansard','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un Sac de sport Adidas','2019-12-11',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un Sac de sport Adidas','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un Casque Audio Philips','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un Casque Audio Philips','2019-12-12',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un Casque Audio Philips','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une Gourde Thermos +Trousse de toilette \"Hibou\"\"\"','2019-12-23',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Bande dessiné Gaston Lagaffe \"Fait un carton\"\"\"','2019-12-11',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Montre Geo Naute','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Eau de parfum Pacco Rabanne \"Olympéa\"\" 80ml + Un collier fantaisie noir\"','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Eau de toilette Pacco Rabane \"Invictus\"\" 100ml + Un collier fantaisie black & white\"','2019-12-11',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Eau de parfum Lanvin \"Eclat d\'arpčge\"\" 100ml + Un collier fantaisie grappe de raisin\"','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Eau de toilette Cacharel \"Anaďs Anaďs\"\" 100ml + Un collier fantaisie \"\"motif géométrique\"\"\"','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Eau de parfum Giorgio Armani \"Sky di Gioia\"\" 100ml + Un collier fantaisie pendentif\"','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Parfum Giorgio Armani \"Acqua Di Gio\"\" 75ml\"','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Clé USB Sodistrel 8Go + Un Mug avec couvercle','2019-12-23',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Bouteille de Champagne Brut Duval-Leroy ','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Serviette de bain 100x180 ','2019-12-23',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Coffret de 4 couteaux de cuisine Pradel ','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une boite de bonbon Haribo 700g','2019-12-06',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Eau de toilette Versace \"Dreamer\"\" 100ml\"','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Eau de toilette Kenzo \"Flower by Kenzo\"\" 50ml\"','2019-12-11',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une Horloge mural ','2019-12-12',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un Ballon de foot + un Mug','2019-12-06',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un Ballon de foot + un Mug','2019-12-23',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Théiere en verre \"Natural \'Tea\"\" 350ml \"','2019-12-12',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Théiere en verre \"Natural \'Tea\"\" 350ml \"','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Lampe flash de running  + Brassard pour téléphone portable','2019-12-23',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Carte Illicado 10€','2019-12-01',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Carte Illicado 10€','2019-12-11',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Carte Illicado 10€','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Carte Illicado 10€','2019-12-06',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Jeu best of cebrity','2019-12-10',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Jeu \"ta mčre en slip\"\"\"','2019-12-11',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une peluche Panda 47 cm','2019-12-01',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un Baby foot de bureau','2019-12-22',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un Nerf X shot','2019-12-10',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Le Livre Guiness des Records 2020','2019-12-05',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une piscine ŕ Mojito','2019-12-22',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une Planche apéro Rock','2019-12-06',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une Planche apéro tour de France','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('LE Calendrier des pompiers 2020','2019-12-23',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Escape game \"Casa de papel\"\"\"','2019-12-05',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un dvd Disney \"Vaina\"\"\"','2019-12-10',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un dvd Disney \"Les nouveaux héros\"\"\"','2019-12-12',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un Coffret Mug \"Peaky Blinders\"\"\"','2019-12-23',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un coffret DVD \"Rio & Epic\"\"\"','2019-12-01',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un appareil photo jetable Fuji ','2019-12-22',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un CD Bohemian Rhapsody','2019-12-05',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une BD \"La fille d\'Asterix\"\"\"','2019-12-10',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Jeu Casse Tęte \"Soirée Enigme\"\"\"','2019-12-23',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un Calendrier \"365 jrs pour avoir le smile\"\"\"','2019-12-05',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un Calendrier \"Truc inutiles ŕ savoir\"\"\"','2019-12-22',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un Calendrier \"365 jrs d\'humour\"\"\"','2019-12-23',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un Calendrier \" 365 blagues monsieur & madame\"\"\"','2019-12-10',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un DVD \"L\'age de glace 4\"\"\"','2019-12-23',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un DVD \"Snoopy\"\"\"','2019-12-22',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un DVD \"Skyfall\"\"\"','2019-12-01',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un appareil Fiesta 3 en 1','2019-12-23',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un rasoir Electrique philipps \"Close Shave\"\"\"','2019-12-05',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un set de 3 couteaux \"Jean Dubost\"\" de Pradel\"','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un Lot de 3 Chopes \"Brasseur 40Cl\"\"\"','2019-12-10',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un set de cuisine 3 pičces \"kitchen Touch\"\"\"','2019-12-21',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Coffret dégustation \"Mélusine et son lot de 3 Terrines\"\"\"','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Coffret dégustation \"Vin Biologique et son lot de Terrine\"\"\"','2019-12-05',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Coffret dégustation \"Emotion et son lot de Terrine\"\"\"','2019-12-09',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Coffret dégustation \"Légende d\'exception et son lot de Terrine\"\"\"','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Dégustation de cochon au sel de Guérande 330g et son Saumur Champigny','2019-12-13',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une enceinte Pink Muse','2019-12-12',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une enceinte Blue Muse','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Coffret beauté Monoď','2019-12-09',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Coffret beauté \"Nuit d\'évasion \"\"\"','2019-12-21',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Coffret dégustation Rhum Cubain \"Presidenté\"\"\"','2019-12-13',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un Magnum Alsace 2017 \"Henri Ehrhart \"\"\"','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un Coffret dégustation bičre \"Kwak\"\" et son verre\"','2019-12-01',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un Magnum Bordeaux Médaille d\'or 2019 \"Château Franc Coupet\"\" \"','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un coffret dégustation \"La goudale \"\" Médaille d\'or 2019 + Verres\"','2019-12-09',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un coffret dégustation \"La  chouffe\"\" + verre\"','2019-12-21',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un coffret Kinder surprise','2019-12-13',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un coffret Kinder surprise','2019-12-17',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un coffret Kinder surprise','2019-12-02',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un coffret Kinder surprise','2019-12-17',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une boîte de chocolat Boules Lindor','2019-12-09',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une boîte de chocolat Boules Lindor','2019-12-17',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une boîte de chocolat Boules Lindor','2019-12-18',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une boîte de chocolat Boules Lindor','2019-12-13',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une boîte de chocolat Boules Lindor','2019-12-02',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une boîte de Ferrero Rocher','2019-12-17',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une boîte de Ferrero Rocher','2019-12-16',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une boîte de Ferrero Rocher','2019-12-09',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une boîte de Ferrero Rocher','2019-12-17',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une boîte de Ferrero Rocher','2019-12-06',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une boîte de Ferrero Rocher','2019-12-17',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un mčtre de chocolat Kinder','2019-12-13',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un mčtre de chocolat Kinder','2019-12-09',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de chocolat Célébrations','2019-12-18',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de chocolat Célébrations','2019-12-05',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de chocolat Célébrations','2019-12-04',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de chocolat Célébrations','2019-12-18',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de chocolat Célébrations','2019-12-02',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de chocolat Célébrations','2019-12-08',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de chocolat Célébrations','2019-12-21',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de chocolat Célébrations','2019-12-13',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une boîte de \"Moments Ferrero\"\"\"','2019-12-06',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une boîte de \"Moments Ferrero\"\"\"','2019-12-18',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une boîte de \"Moments Ferrero\"\"\"','2019-12-16',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une boîte de \"Moments Ferrero\"\"\"','2019-12-02',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une boîte de \"Moments Ferrero\"\"\"','2019-12-20',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de champagne \"Nicolas Feuillatte\"\"\"','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de champagne \"Nicolas Feuillatte\"\"\"','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de champagne \"Nicolas Feuillatte\"\"\"','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de champagne \"Nicolas Feuillatte\"\"\"','2019-12-04',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de champagne \"Nicolas Feuillatte\"\"\"','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de champagne \"Nicolas Feuillatte\"\"\"','2019-12-07',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de château \"Bousquet\"\"\"','2019-12-16',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de château \"Bousquet\"\"\"','2019-12-18',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de château \"Bousquet\"\"\"','2019-12-03',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de château \"Bousquet\"\"\"','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de château \"Bousquet\"\"\"','2019-12-13',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de château  \"Puybarbe\"\"\"','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de château  \"Puybarbe\"\"\"','2019-12-18',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de château  \"Puybarbe\"\"\"','2019-12-08',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de château  \"Puybarbe\"\"\"','2019-12-07',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de château  \"Puybarbe\"\"\"','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de coteaux de l\'aubance \"Elysis\"\"\"','2019-12-07',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de coteaux de l\'aubance \"Elysis\"\"\"','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de coteaux de l\'aubance \"Elysis\"\"\"','2019-12-04',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de coteaux de l\'aubance \"Elysis\"\"\"','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de coteaux de l\'aubance \"Elysis\"\"\"','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de coteaux de l\'aubance \"Elysis\"\"\"','2019-12-03',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de Gewurztraminer \"Rosenhof\"\"\"','2019-12-16',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de Gewurztraminer \"Rosenhof\"\"\"','2019-12-19',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de Gewurztraminer \"Rosenhof\"\"\"','2019-12-14',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de Gewurztraminer \"Rosenhof\"\"\"','2019-12-19',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de Gewurztraminer \"Rosenhof\"\"\"','2019-12-07',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de blanc Foussy \"ICE\"\"\"','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de blanc Foussy \"ICE\"\"\"','2019-12-15',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de Crémant \"Petite folie ICE\"\"\"','2019-12-20',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Une bouteille de Crémant \"Petite folie ICE\"\"\"','2019-12-19',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un jeu \"JUDUKU\"\" La fesse cachée\"','2019-12-02',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un Molkky','2019-12-08',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un Harmonica Bleu','2019-12-16',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un véritable UKULELE','2019-12-24',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un jeu une énigme par jour','2019-12-20',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un jeu \"coup de pute\"\"\"','2019-12-14',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un Mug collector \"La casa de papel\"\"\"','2019-12-04',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un calendrier 2020 Yann Arthus Bertrand','2019-12-14',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un calendrier 2020 \"Ombre et lumičre\"\"\"','2019-12-15',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un calendrier 2020 \"Alors ça pique\"\"\"','2019-12-19',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un jeu \"LOBO 77\"\"\"','2019-12-08',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un dvd \"Jeff Panacloc contre attaque\"\"\"','2019-12-03',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un calendrier 365 blagues qui tuent','2019-12-16',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un calendrier 365 jours licorne','2019-12-15',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un jeu blanc manger coco \"La petite gaterie\"\"\"','2019-12-19',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un jeu blanc manger coco \" Le déluge\"\"\"','2019-12-03',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un coffret \"Sushi bar\"\"\"','2019-12-20',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un jeu Dobble classic','2019-12-14',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un jeu Quiz \"Apéro 100% BZH\"\"\"','2019-12-07',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un jeu \"Apéro menteur\"\" \"','2019-12-20',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un jeu apéro \"Tu préfčres…\"\"\"','2019-12-08',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un dvd \"Le grand bain\"\"\"','2019-12-04',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un dvd \"A star is born\"\"\"','2019-12-15',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un dvd \" Bohemian Rhapsody\"','2019-12-20',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Le jeu \"Burger Quiz\"\"\"','2019-12-03',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Le jeu \"6 qui prend\"\"\"','2019-12-19',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Le jeu \"joke de papa\"\"\"','2019-12-07',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un jeu escape game \"Le triangle des bermudes\"\"\"','2019-12-14',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un jeu \"Zapping de la culture générale\"\"\"','2019-12-15',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Le double Dvd \"Comment tuer son boss\"\"\"','2019-12-04',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Le jeu la boîte ŕ quiz \"Guide du routard\"\"\"','2019-12-15',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('L\'atlas \"Le gorafi des régions\"\"\"','2019-12-08',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Un jeu escpae game \"Prison scape\"\"\"','2019-12-14',NULL,NULL);
INSERT INTO `cadeau` (`Description`,`Agagner`,`dateGain`,`user_app_iduser_app`) VALUES ('Le monopoly \"Edition tricheur\"\"\"','2019-12-03',NULL,NULL);
